### ISSUE TITLE
Load of data error

### ISSUE THREAD

**Issue by thisislohith6** [skatsuta/vrp-solver#2]
Hi Skatsuta,

While running your code, I'm facing some error by loading the dataset. Could you please help me with that.

Error:
usage: solver.py [-h] [-g] [--gls] [-v] path
solver.py: error: the following arguments are required: path

Thanks in advance!

**Comment by skatsuta** [comment]
You have to specify a YAML file that represents a vehicle routing problem you want to solve as the first argument.
Please read https://github.com/skatsuta/vrp-solver#usage section in README and follow the instruction.
If you still have an issue, feel free to reopen it.
